<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'">
    <DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="croizat.clib" Version="1.0.53" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommons\ECommons\ECommons.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
  </ItemGroup>
</Project>
